apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: eshopwebmvc
  name: eshopwebmvc
spec:
  ports:
  - name: "http"
    port: 80
  selector:
    io.kompose.service: eshopwebmvc
  type: LoadBalancer